name: Deploy

# Trigger the workflow on push and
# pull request events on the production branch
on: push

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: testing
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Verify MySQL connection
        run: |
          mysql --version
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -psecret -e "SHOW DATABASES"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install Dependencies
        run: composer install

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          MYSQL_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: secret
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          php artisan test
  deploy:
    needs:
      - testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Despliegue al entorno de produccion API
        uses: appleboy/ssh-action@master
        with:
          host: ${{vars.API_HOST}}
          username: ${{vars.DEFAULT_DEPLOY_USER}}
          key: ${{ secrets.API_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/api.aveonline.co/web

            if [ -d 'webhook-interrapidisimo' ]
            then
                cd webhook-interrapidisimo
                git config --global --add safe.directory /var/www/clients/client1/web1/web/webhook-interrapidisimo
                git pull origin master
            else
                git clone  git@github.com:Development-Aveonline/webhook-interrapidisimo.git
                cd webhook-interrapidisimo
                git config --global --add safe.directory /var/www/clients/client1/web1/web/webhook-interrapidisimo
            fi
            php8.1 /usr/local/bin/composer install
            git config pull.rebase false
            php8.1 artisan env:decrypt --key=${{ secrets.KEY_ENV }} --force
            php8.1 artisan optimize:clear
            php8.1 artisan openapi:generate
            chown web1:client1 -R .
            git status
